//import * as ACTIONS from '../actions/Actions';

export const SET_CONFIG ='SET_CONFIG';
export const SET_DEFAULT_USER = 'SET_DEFAULT_USER';
export const SET_CONTENT = 'SET_CONTENT';
export const SET_CURRENT_STRUCTURE = 'SET_CURRENT_STRUCTURE';
export const SET_CURRENT_STRUCTURE_DATES = 'SET_CURRENT_STRUCTURE_DATES';
export const SET_LRS_STATEMENTS = 'SET_LRS_STATEMENTS';
export const SET_SHADOW_ENROLLMENTS = 'SET_SHADOW_ENROLLMENTS';
export const SET_FULL_USER_PROFILE = 'SET_FULL_USER_PROFILE';
export const SET_ENROLLED_COURSES = 'SET_ENROLLED_COURSES';
export const SET_USER_CALENDAR = 'SET_USER_CALENDAR';
export const SET_COURSES_IN_MAP = 'SET_COURSES_IN_MAP';
